# Generated by Django 4.1.4 on 2024-02-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='test',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
