# Generated by Django 4.1.4 on 2024-02-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_document_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='test',
        ),
    ]
