# Generated by Django 4.1.4 on 2024-02-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_distributor_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='qr code'),
        ),
    ]
