# Generated by Django 4.1.4 on 2024-02-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_purchaseorder_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePOType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสประเภทใบสั่งซื้อ')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อประเภทใบสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'ประเภทใบสั่งซื้อ',
                'verbose_name_plural': 'ข้อมูลประเภทใบสั่งซื้อ',
                'db_table': 'BasePOType',
                'ordering': ('id',),
            },
        ),
    ]
