# Generated by Django 3.2.3 on 2021-06-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_requisition_requisitionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='desired_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='machine',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
