# Generated by Django 4.1.4 on 2024-02-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_basepotype'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basepotype'),
        ),
    ]
