# Generated by Django 3.2.3 on 2021-06-22 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stock', '0007_auto_20210622_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
