# Generated by Django 4.1.4 on 2024-05-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_purchaseorder_po_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRepairType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสประเภทการซ่อม')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อประเภทการซ่อม')),
            ],
            options={
                'verbose_name': 'แท็บประเภทการซ่อม',
                'verbose_name_plural': 'ข้อมูลประเภทการซ่อม',
                'db_table': 'BaseRepairType',
                'ordering': ('id',),
            },
        ),
    ]
