# Generated by Django 3.2.3 on 2021-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_cruduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseApproveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'BaseApproveStatus',
                'ordering': ('id',),
            },
        ),
    ]
