# Generated by Django 4.1.4 on 2024-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_requisition_car_requisition_repair_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
