# Generated by Django 3.2.3 on 2021-06-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_baseapprovestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='chief_approve_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.baseapprovestatus'),
            preserve_default=False,
        ),
    ]
