# Generated by Django 4.1.4 on 2024-06-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_comparisonprice_note_alter_purchaseorder_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBrokeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อเหตุผล/สาเหตุที่ต้องซ่อม')),
            ],
            options={
                'verbose_name': 'เหตุผล/สาเหตุที่ต้องซ่อม',
                'verbose_name_plural': 'ข้อมูลเหตุผล/สาเหตุที่ต้องซ่อม',
                'db_table': 'BaseBrokeType',
                'ordering': ('id',),
            },
        ),
    ]
