# Generated by Django 4.1.4 on 2024-07-01 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_baserequisitiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype'),
        ),
    ]
