# Generated by Django 4.1.4 on 2024-07-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_requisition_rq_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebroketype',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype'),
        ),
        migrations.AddField(
            model_name='baserepairtype',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype'),
        ),
    ]
