# Generated by Django 4.1.4 on 2024-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_basebroketype_rq_type_baserepairtype_rq_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecar',
            options={'ordering': ('id',), 'verbose_name': 'เครื่องจักร/ทะเบียนรถ', 'verbose_name_plural': 'ข้อมูลเครื่องจักร/ทะเบียนรถ'},
        ),
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อเครื่องจักร/ทะเบียนรถ'),
        ),
    ]
