# Generated by Django 4.1.4 on 2024-07-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_basecar_options_alter_basecar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecar',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype'),
        ),
    ]
