# Generated by Django 3.2.3 on 2021-06-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20210629_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='desired_date',
            field=models.DateField(default=1,blank=True, null=True),
            preserve_default=False,
        ),
    ]
