# Generated by Django 4.1.4 on 2024-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_basecar_rq_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExpenseDepartment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสแผนกค่าใช้จ่าย')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อแผนกค่าใช้จ่าย')),
            ],
            options={
                'verbose_name': 'แผนกค่าใช้จ่าย',
                'verbose_name_plural': 'ข้อมูลแผนกค่าใช้จ่าย',
                'db_table': 'BaseExpenseDepartment',
                'ordering': ('id',),
            },
        ),
    ]
