# Generated by Django 4.1.4 on 2024-07-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_requisition_desired_date_requisition_expense_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserequisitiontype',
            name='iso_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='iso code'),
        ),
    ]
