# Generated by Django 4.1.4 on 2024-07-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_baserequisitiontype_iso_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExpenses',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสค่าใช้จ่าย')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อค่าใช้จ่าย')),
            ],
            options={
                'verbose_name': 'ค่าใช้จ่าย',
                'verbose_name_plural': 'ข้อมูลค่าใช้จ่าย',
                'db_table': 'BaseExpenses',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='basebroketype',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype', verbose_name='ประเภทใบขอเบิก'),
        ),
        migrations.AlterField(
            model_name='basecar',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype', verbose_name='ประเภทใบขอเบิก'),
        ),
        migrations.AlterField(
            model_name='baserepairtype',
            name='rq_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserequisitiontype', verbose_name='ประเภทใบขอเบิก'),
        ),
    ]
