# Generated by Django 4.1.4 on 2024-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_baseexpenses_alter_basebroketype_rq_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='expenses',
            field=models.ManyToManyField(blank=True, null=True, to='stock.baseexpenses', verbose_name='ค่าใช้จ่าย'),
        ),
    ]
