# Generated by Django 4.1.4 on 2024-07-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_remove_requisition_is_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุ/เหตุผล'),
        ),
    ]
