# Generated by Django 3.2.5 on 2021-07-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_alter_requisition_section'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisition',
            table='Requisitions',
        ),
    ]
