# Generated by Django 4.1.4 on 2024-07-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_requisition_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='basebranchcompany',
            name='bill_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โค้ดใบจ่ายสินค้าภายใน'),
        ),
    ]
