# Generated by Django 4.1.4 on 2024-07-24 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0028_rename_bill_code_basebranchcompany_invoice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('branch_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany')),
                ('bring_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bring_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เบิก')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecar', verbose_name='หมายเหตุ')),
                ('expense_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่าย')),
                ('payer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จ่าย')),
            ],
            options={
                'db_table': 'Invoice',
                'ordering': ('-id',),
                'unique_together': {('ref_no', 'branch_company')},
            },
        ),
    ]
