# Generated by Django 3.2.5 on 2021-07-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_alter_requisition_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisition',
            table='RequisitionDoc',
        ),
    ]
