# Generated by Django 3.2.5 on 2021-07-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stock', '0030_alter_requisition_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requisition',
            new_name='RequisitionDoc',
        ),
    ]
