# Generated by Django 4.1.4 on 2024-07-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='requisit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.requisition'),
        ),
    ]
