# Generated by Django 4.1.4 on 2024-07-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_invoice_requisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
