# Generated by Django 4.1.4 on 2024-08-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_alter_invoiceitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'หน่วยงาน',
                'verbose_name_plural': 'ข้อมูลหน่วยงาน',
                'db_table': 'BaseAgency',
                'ordering': ('id',),
            },
        ),
    ]
