# Generated by Django 4.1.4 on 2024-08-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_baseexpensedepartment_aagency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseexpensedepartment',
            old_name='aagency',
            new_name='agency',
        ),
    ]
