# Generated by Django 4.1.4 on 2024-09-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_comparisonpriceitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecar',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อเครื่องจักร/ทะเบียนรถ'),
        ),
        migrations.AlterUniqueTogether(
            name='basecar',
            unique_together={('name', 'code')},
        ),
    ]
