# Generated by Django 4.1.4 on 2024-09-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_basecar_code_alter_basecar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อเครื่องจักร/ทะเบียนรถ'),
        ),
    ]
