# Generated by Django 4.1.4 on 2024-09-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0039_alter_basecar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecar',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อเครื่องจักร/ทะเบียนรถ'),
        ),
    ]
