# Generated by Django 4.1.4 on 2024-09-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_alter_basecar_code_alter_basecar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecar',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='code'),
        ),
    ]
