# Generated by Django 4.1.4 on 2024-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_alter_basecar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อเครื่องจักร/ทะเบียนรถ'),
        ),
    ]
