# Generated by Django 4.1.4 on 2024-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_alter_basecar_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecar',
            options={'ordering': ('id',), 'verbose_name': 'เครื่องจักร/ทะเบียนรถ/หน่วยงาน', 'verbose_name_plural': 'ข้อมูลเครื่องจักร/ทะเบียนรถ/หน่วยงาน'},
        ),
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อเครื่องจักร/ทะเบียนรถ/หน่วยงาน'),
        ),
    ]
