# Generated by Django 3.2.5 on 2021-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_auto_20210715_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_id', models.IntegerField(blank=True, null=True)),
                ('examiner_user_id', models.IntegerField(blank=True, null=True)),
                ('examiner_status', models.CharField(blank=True, max_length=255)),
                ('stockman_user_id', models.IntegerField(blank=True, null=True)),
                ('stockman_status', models.CharField(blank=True, max_length=255)),
                ('approver_user_id', models.IntegerField(blank=True, null=True)),
                ('approver_status', models.CharField(blank=True, max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
