# Generated by Django 4.1.4 on 2024-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_alter_basecar_options_alter_basecar_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecar',
            options={'ordering': ('id',), 'verbose_name': 'ทะเบียนรถ/เครื่องจักร/หน่วยงาน', 'verbose_name_plural': 'ข้อมูลทะเบียนรถ/เครื่องจักร/หน่วยงาน'},
        ),
        migrations.AlterField(
            model_name='basecar',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ชื่อทะเบียนรถ/เครื่องจักร/หน่วยงาน'),
        ),
    ]
