# Generated by Django 4.1.4 on 2024-10-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_alter_basecar_options_alter_basecar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='invoice_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
