# Generated by Django 4.1.4 on 2024-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_requisition_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='iv_ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
