# Generated by Django 3.2.5 on 2021-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_auto_20210716_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requisition_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
