# Generated by Django 3.2.5 on 2021-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_alter_purchaserequisition_requisition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='purchase_requisition_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
