# Generated by Django 4.1.4 on 2024-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_alter_requisition_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='mile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขไมค์'),
        ),
    ]
