# Generated by Django 3.2.5 on 2021-07-17 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_baseurgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.baseurgency'),
        ),
    ]
