# Generated by Django 3.2.5 on 2021-07-17 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_auto_20210717_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseurgency',
            options={'ordering': ('id',), 'verbose_name': 'ระดับความเร่งด่วน', 'verbose_name_plural': 'ข้อมูลระดับความเร่งด่วน'},
        ),
    ]
