# Generated by Django 4.1.4 on 2024-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0049_alter_requisition_mile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='mile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขไมล์/เลขชั่วโมง'),
        ),
    ]
