# Generated by Django 4.1.4 on 2025-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0050_alter_requisition_mile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
