# Generated by Django 4.1.4 on 2025-01-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_alter_comparisonpriceitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
