# Generated by Django 4.1.4 on 2025-01-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_alter_comparisonpricedistributor_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
