# Generated by Django 4.1.4 on 2025-01-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0056_alter_comparisonprice_amount_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
