# Generated by Django 3.2.5 on 2021-07-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0057_alter_purchaserequisition_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='temp',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
