# Generated by Django 4.1.4 on 2025-01-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0057_alter_purchaseorderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
