# Generated by Django 4.1.4 on 2025-01-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0058_alter_invoiceitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approver_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
