# Generated by Django 4.1.4 on 2025-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_alter_purchaserequisition_approver_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='purchase_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='stockman_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
