# Generated by Django 4.1.4 on 2025-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_alter_purchaserequisition_purchase_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='approver_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonprice',
            name='examiner_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonprice',
            name='special_approver_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
