# Generated by Django 3.2.5 on 2021-07-19 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_purchaserequisition_temp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequisition',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requisition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.requisition'),
        ),
    ]
