# Generated by Django 4.1.4 on 2025-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0061_alter_comparisonprice_approver_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approver_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
