# Generated by Django 3.2.5 on 2021-07-21 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0063_alter_requisitionitem_requisition_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepermission',
            options={'ordering': ('id',), 'verbose_name': 'สิทธิการทำงาน', 'verbose_name_plural': 'ข้อมูลสิทธิการทำงาน'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('id',), 'verbose_name': 'ตำแหน่งงาน', 'verbose_name_plural': 'ข้อมูลตำแหน่งงาน'},
        ),
        migrations.AlterModelOptions(
            name='positionbasepermission',
            options={'ordering': ('id',), 'verbose_name': 'ตำแหน่งงานและสิทธิการทำงาน', 'verbose_name_plural': 'ข้อมูลตำแหน่งงานและสิทธิการทำงาน'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
