# Generated by Django 4.1.4 on 2025-04-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0064_requisition_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExOESTND',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('docnum', models.CharField(blank=True, max_length=12, null=True)),
                ('seqnum', models.IntegerField(blank=True, null=True)),
                ('loccod', models.CharField(blank=True, max_length=10, null=True)),
                ('comcod', models.CharField(blank=True, max_length=10, null=True)),
                ('stktyp', models.CharField(blank=True, max_length=10, null=True)),
                ('stkcod', models.CharField(blank=True, max_length=20, null=True)),
                ('stkdes', models.CharField(blank=True, max_length=60, null=True)),
                ('ordqty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tfactor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unitpr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tqucod', models.CharField(blank=True, max_length=10, null=True)),
                ('trnval', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unitnam', models.CharField(blank=True, max_length=35, null=True)),
                ('stknote', models.CharField(blank=True, max_length=50, null=True)),
                ('audtuser', models.CharField(blank=True, max_length=50, null=True)),
                ('audttime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OESTND',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExOESTNH',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('docnum', models.CharField(blank=True, max_length=12, null=True)),
                ('docdat', models.DateField(blank=True, null=True)),
                ('posopr', models.CharField(blank=True, max_length=1, null=True)),
                ('depcod', models.CharField(blank=True, max_length=2, null=True)),
                ('loccod', models.CharField(blank=True, max_length=4, null=True)),
                ('refnum', models.CharField(blank=True, max_length=12, null=True)),
                ('comcod', models.CharField(blank=True, max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=120, null=True)),
                ('note1', models.CharField(blank=True, max_length=120, null=True)),
                ('note2', models.CharField(blank=True, max_length=120, null=True)),
                ('note3', models.CharField(blank=True, max_length=120, null=True)),
                ('audtuser', models.CharField(blank=True, max_length=120, null=True)),
                ('audttime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OESTNH',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
