# Generated by Django 3.2.5 on 2021-07-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0064_auto_20210721_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='approver_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='examiner_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='stockman_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
