# Generated by Django 4.1.4 on 2025-04-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0065_exoestnd_exoestnh_invoice_is_express_invoice_v_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='v_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
