# Generated by Django 4.1.4 on 2025-04-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0067_invoice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='is_re_approve',
            field=models.BooleanField(default=False),
        ),
    ]
