# Generated by Django 3.2.5 on 2021-07-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0068_auto_20210721_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='reference_id',
        ),
    ]
