# Generated by Django 4.1.4 on 2025-04-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0069_exoeinvd_exoeinvh_exvwiv01_exvwiv02_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExVWIV01',
        ),
        migrations.DeleteModel(
            name='ExVWIV02',
        ),
    ]
