# Generated by Django 4.1.4 on 2025-05-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0070_delete_exvwiv01_delete_exvwiv02'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='pd_qr_codes/', verbose_name='qr code'),
        ),
    ]
