# Generated by Django 3.2.5 on 2021-07-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0070_rename_examiner_user_id_purchaserequisition_examiner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='urgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseurgency'),
        ),
    ]
