# Generated by Django 4.1.4 on 2025-08-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0071_product_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
                ('column3', models.CharField(max_length=255)),
            ],
        ),
    ]
