# Generated by Django 3.2.5 on 2021-07-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0071_requisition_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_express',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
