# Generated by Django 4.1.4 on 2025-08-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0072_testsheetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='รหัสการซ่อม')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('car', models.CharField(blank=True, max_length=255, null=True, verbose_name='ทะเบียนรถ')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้แจ้งซ่อม')),
                ('broke_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='อาการเสีย')),
                ('car_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='สภาพรถ')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='รูปภาพที่ 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='รูปภาพที่ 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='รูปภาพที่ 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='maintenance/', verbose_name='รูปภาพที่ 4')),
                ('branch_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany')),
            ],
            options={
                'db_table': 'Maintenance',
                'ordering': ('-id',),
            },
        ),
    ]
