# Generated by Django 4.1.4 on 2025-08-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0073_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
