# Generated by Django 3.2.5 on 2021-07-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0073_auto_20210729_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequisition',
            old_name='examiner_update',
            new_name='purchase_update',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='examiner_status',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='examiner_user',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='stockman_status',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='stockman_update',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='stockman_user',
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='purchase_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_status', to='stock.baseapprovestatus'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='purchase_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
