# Generated by Django 4.1.4 on 2025-08-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0074_maintenance_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
