# Generated by Django 3.2.5 on 2021-07-30 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0074_auto_20210730_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='stockman_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockman_status', to='stock.baseapprovestatus'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='stockman_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='stockman_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockman_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
