# Generated by Django 3.2.5 on 2021-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0075_auto_20210730_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='stockman_status',
        ),
    ]
