# Generated by Django 4.1.4 on 2025-08-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0075_alter_maintenance_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestSheetData',
        ),
    ]
