# Generated by Django 4.1.4 on 2025-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0076_delete_testsheetdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='approve_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้อนุมัติซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='approve_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานะอนุมัติซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='approve_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
