# Generated by Django 4.1.4 on 2025-08-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0077_maintenance_approve_name_maintenance_approve_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress'),
        ),
    ]
