# Generated by Django 4.1.4 on 2025-08-14 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0078_maintenance_address_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='broke_type',
            new_name='broke_reason',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='approve_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_ap_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติซ่อม'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecar'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้งซ่อม'),
        ),
    ]
