# Generated by Django 4.1.4 on 2025-08-14 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0079_rename_broke_type_maintenance_broke_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_ch_name', to=settings.AUTH_USER_MODEL, verbose_name='หัวหน้าช่างซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='อธิบายงาน/รายละเอียด'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='end_rp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่กำหนดเสร็จ'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานที่ซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='repair_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_rp_name', to=settings.AUTH_USER_MODEL, verbose_name='ช่างซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='start_rp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่เริ่มดำเนินการ'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='sum_up',
            field=models.TextField(blank=True, null=True, verbose_name='สรุปงานซ่อม/ความคิดเห็น'),
        ),
    ]
