# Generated by Django 3.2.5 on 2021-08-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0079_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
