# Generated by Django 4.1.4 on 2025-08-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0080_maintenance_chief_maintenance_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='chief',
            new_name='chief_name',
        ),
    ]
