# Generated by Django 4.1.4 on 2025-08-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0081_rename_chief_maintenance_chief_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMAType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสประเภทใบแจ้งซ่อม')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อประเภทใบแจ้งซ่อม')),
            ],
            options={
                'verbose_name': 'ประเภทใบแจ้งซ่อม',
                'verbose_name_plural': 'ข้อมูลประเภทใบแจ้งซ่อม',
                'db_table': 'BaseMAType',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='ma_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basematype'),
        ),
    ]
