# Generated by Django 4.1.4 on 2025-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0082_basematype_maintenance_ma_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='fail_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ปิดสรุปไม่ได้'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
