# Generated by Django 4.1.4 on 2025-08-15 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0083_maintenance_fail_reason_maintenance_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.distributor'),
        ),
    ]
