# Generated by Django 3.2.5 on 2021-08-18 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0083_remove_purchaseorderitem_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='po',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaseorder'),
            preserve_default=False,
        ),
    ]
