# Generated by Django 3.2.5 on 2021-08-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0084_purchaseorderitem_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaseorder'),
        ),
    ]
