# Generated by Django 3.2.5 on 2021-08-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0085_alter_purchaseorderitem_po'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='po',
        ),
    ]
