# Generated by Django 4.1.4 on 2025-08-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0085_maintenance_repair_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='chief_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
