# Generated by Django 4.1.4 on 2025-08-19 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stock.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0086_maintenance_chief_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='contact_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_ct_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='force_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='ใช้แรง (วัน)'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='force_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='ใช้แรง (ชม.)'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='ma_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/maintenance/%Y/%m/%d', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='repair_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baserepairtype'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='sender_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_sd_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดส่งงาน'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='work_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='ชม.ทำงาน (ชม.)'),
        ),
    ]
