# Generated by Django 4.1.4 on 2025-08-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0087_maintenance_contact_name_maintenance_force_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='ma_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='ma_ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
