# Generated by Django 4.1.4 on 2025-08-25 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0088_requisition_ma_id_requisition_ma_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarLogbook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='รหัสบันทึกการใช้รถ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('oil', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำมันโซล่า ( ลิตร )')),
                ('engine', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำมันเครื่อง ( ลิตร )')),
                ('hydraulic', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำมันไฮโดรลิค ( ลิตร )')),
                ('grease', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='จารบี ( ลิตร )')),
                ('mile_start', models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่ม')),
                ('mile_end', models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุด')),
                ('job1', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดงานที่ 1')),
                ('start_job1', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มงานที่ 1')),
                ('end_job1', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุดงานที่ 1')),
                ('job2', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดงานที่ 2')),
                ('start_job2', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มงานที่ 2')),
                ('end_job2', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุดงานที่ 2')),
                ('job3', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดงานที่ 3')),
                ('start_job3', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มงานที่ 3')),
                ('end_job3', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุดงานที่ 3')),
                ('job4', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดงานที่ 4')),
                ('start_job4', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มงานที่ 4')),
                ('end_job4', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุดงานที่ 4')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('address_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress')),
                ('branch_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecar')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_name', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึกการใช้รถ')),
            ],
            options={
                'db_table': 'CarLogbook',
                'ordering': ('-id',),
            },
        ),
    ]
