# Generated by Django 3.2.5 on 2021-08-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0089_auto_20210819_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.requisitionitem'),
        ),
    ]
