# Generated by Django 4.1.4 on 2025-08-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0089_carlogbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
