# Generated by Django 4.1.4 on 2025-08-25 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0090_carlogbook_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='mile',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขตอนแจ้งซ่อม'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_og_name', to=settings.AUTH_USER_MODEL, verbose_name='พัสดุซ่อมบำรุง (ผู้จัดทำ)'),
        ),
    ]
