# Generated by Django 3.2.5 on 2021-08-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0091_auto_20210823_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Distributor',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='customer',
            new_name='distributor',
        ),
        migrations.AlterModelTable(
            name='distributor',
            table='Distributor',
        ),
    ]
