# Generated by Django 4.1.4 on 2025-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0091_maintenance_mile_maintenance_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='รหัสการซ่อม'),
        ),
    ]
