# Generated by Django 4.1.4 on 2025-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0092_alter_carlogbook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='series',
            field=models.IntegerField(blank=True, null=True, verbose_name='ลำดับ'),
        ),
    ]
