# Generated by Django 3.2.5 on 2021-08-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0092_auto_20210823_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'BaseVatType',
                'ordering': ('id',),
            },
        ),
    ]
