# Generated by Django 3.2.5 on 2021-08-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0093_basevattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basevattype'),
        ),
    ]
