# Generated by Django 4.1.4 on 2025-08-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0093_carlogbook_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
