# Generated by Django 4.1.4 on 2025-08-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0094_alter_carlogbook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='car_tail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_car2', to='stock.basecar', verbose_name='ทะเบียนรถ (หาง)'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_car1', to='stock.basecar', verbose_name='ทะเบียนรถ'),
        ),
    ]
