# Generated by Django 4.1.4 on 2025-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0095_carlogbook_car_tail_alter_carlogbook_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='job5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดงานที่ 5'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='job6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียดงานที่ 6'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_end_job1',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 1'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_end_job2',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 2'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_end_job3',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 3'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_end_job4',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 4'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_end_job5',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 5'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_end_job6',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 6'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_start_job1',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 1'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_start_job2',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 2'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_start_job3',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 3'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_start_job4',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 4'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_start_job5',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 5'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='mile_start_job6',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 6'),
        ),
    ]
