# Generated by Django 4.1.4 on 2025-08-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0096_carlogbook_job5_carlogbook_job6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='err_log',
            field=models.TextField(blank=True, null=True, verbose_name='error log'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='err_log',
            field=models.TextField(blank=True, null=True, verbose_name='error log'),
        ),
    ]
