# Generated by Django 4.1.4 on 2025-08-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0097_carlogbook_err_log_maintenance_err_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlogbook',
            options={'ordering': ('-id',), 'verbose_name': 'ใบบันทึกการใช้งานรถ', 'verbose_name_plural': 'ข้อมูลใบบันทึกการใช้งานรถ'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ('-id',), 'verbose_name': 'ใบแจ้งซ่อม', 'verbose_name_plural': 'ข้อมูลใบแจ้งซ่อม'},
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='image_mile',
            field=models.ImageField(blank=True, null=True, upload_to='car_log_book/', verbose_name='รูปภาพเลขไมล์เริ่มต้น'),
        ),
    ]
