# Generated by Django 4.1.4 on 2025-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0098_alter_carlogbook_options_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='image_mile',
            field=models.ImageField(blank=True, null=True, upload_to='car_log_book/%Y/%m/%d', verbose_name='รูปภาพเลขไมล์เริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', verbose_name='รูปภาพที่ 1'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', verbose_name='รูปภาพที่ 2'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', verbose_name='รูปภาพที่ 3'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', verbose_name='รูปภาพที่ 4'),
        ),
    ]
