# Generated by Django 4.1.4 on 2025-09-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0099_alter_carlogbook_image_mile_alter_maintenance_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/เหตุผล'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/เหตุผล'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/เหตุผล'),
        ),
    ]
