# Generated by Django 4.1.4 on 2025-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0100_alter_comparisonprice_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='gas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำเบนซิล ( ลิตร )'),
        ),
    ]
