# Generated by Django 4.1.4 on 2025-09-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0101_carlogbook_gas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
