# Generated by Django 4.1.4 on 2025-09-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0102_alter_purchaseorder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='car_tail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_car2', to='stock.basecar', verbose_name='ทะเบียนรถ (หาง)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_car1', to='stock.basecar', verbose_name='ทะเบียนรถ'),
        ),
    ]
