# Generated by Django 3.2.5 on 2021-08-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0102_auto_20210827_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpriceitem',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.comparisonpricedistributor'),
        ),
    ]
