# Generated by Django 3.2.5 on 2021-08-30 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0103_comparisonpriceitem_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpricedistributor',
            name='cp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.comparisonprice'),
        ),
    ]
