# Generated by Django 4.1.4 on 2025-09-09 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0103_maintenance_car_tail_alter_maintenance_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
    ]
