# Generated by Django 4.2.24 on 2025-09-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0104_alter_carlogbook_created_alter_maintenance_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
