# Generated by Django 4.2.24 on 2025-09-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0105_maintenance_is_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='uniq_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='uniq_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
