# Generated by Django 4.2.24 on 2025-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0106_carlogbook_uniq_code_maintenance_uniq_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
