# Generated by Django 3.2.5 on 2021-08-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0106_rename_cp_comparisonpriceitem_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonpriceitem',
            name='comparison',
        ),
    ]
