# Generated by Django 3.2.5 on 2021-09-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0108_comparisonpriceitem_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
