# Generated by Django 4.2.24 on 2025-09-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0108_alter_maintenance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCarDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน')),
            ],
            options={
                'verbose_name': 'แผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'verbose_name_plural': 'ข้อมูลแผนกแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'db_table': 'BaseCarDepartment',
                'ordering': ('id',),
            },
        ),
    ]
