# Generated by Django 4.2.24 on 2025-09-24 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0109_basecardepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecardepartment', verbose_name='แผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน')),
                ('in_comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany', verbose_name='สังกัดบริษัทที่อยู่')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'ผู้ใช้และแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'verbose_name_plural': 'ข้อมูลผู้ใช้และแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
            },
        ),
    ]
