# Generated by Django 3.2.5 on 2021-09-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0110_comparisonprice_select_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='select_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.distributor'),
        ),
    ]
