# Generated by Django 4.2.24 on 2025-09-24 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0110_usercardepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseJobCarDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='รายละเอียดงาน')),
                ('car_dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecardepartment', verbose_name='แผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน')),
            ],
            options={
                'verbose_name': 'รายละเอียดงานและแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'verbose_name_plural': 'ข้อมูลรายละเอียดงานและแผนกแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'db_table': 'BaseJobCarDep',
                'ordering': ('id',),
            },
        ),
    ]
