# Generated by Django 3.2.5 on 2021-09-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0111_alter_comparisonprice_select_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'หน่วยสินค้า',
                'verbose_name_plural': 'ข้อมูลหน่วยสินค้า',
                'db_table': 'BaseUnit',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='comparisonprice',
            options={'ordering': ('-id',)},
        ),
    ]
