# Generated by Django 4.2.24 on 2025-09-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0111_basejobcardep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardepartment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucd_car1', to='stock.basecar', verbose_name='ทะเบียนรถ'),
        ),
    ]
