# Generated by Django 4.2.24 on 2025-09-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0112_usercardepartment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='mile',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์ตอนแจ้งซ่อม'),
        ),
    ]
