# Generated by Django 4.2.24 on 2025-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0113_alter_maintenance_mile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='รหัสการซ่อม'),
        ),
    ]
