# Generated by Django 4.2.24 on 2025-09-25 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0114_alter_maintenance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveCarDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_company', models.ManyToManyField(to='stock.basebranchcompany', verbose_name='สิทธิการอนุมัติตามบริษัท')),
                ('car_dep', models.ManyToManyField(to='stock.basecardepartment', verbose_name='แผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมติ')),
            ],
            options={
                'verbose_name': 'ผู้อนุม้ติและสิทธิการอนุมัติแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'verbose_name_plural': 'ข้อมูลผู้อนุม้ติและสิทธิการอนุมัติแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน',
                'db_table': 'ApproveCarDepartment',
                'ordering': ('id',),
            },
        ),
    ]
