# Generated by Django 4.2.24 on 2025-10-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0115_approvecardepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='basejobcardep',
            name='expense_dept',
            field=models.ManyToManyField(blank=True, limit_choices_to={'agency__id': 1}, to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่าย'),
        ),
    ]
