# Generated by Django 4.2.24 on 2025-10-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0116_basejobcardep_expense_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='expense_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่าย'),
        ),
    ]
