# Generated by Django 4.2.24 on 2025-10-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0117_carlogbook_expense_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlogbook',
            name='expense_dept',
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='exd_job1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exd_j1', to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่ายงานที่ 1'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='exd_job2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exd_j2', to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่ายงานที่ 2'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='exd_job3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exd_j3', to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่ายงานที่ 3'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='exd_job4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exd_j4', to='stock.baseexpensedepartment', verbose_name='แผนกค่าใช้จ่ายงานที่ 4'),
        ),
    ]
