# Generated by Django 4.2.24 on 2025-10-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0118_remove_carlogbook_expense_dept_carlogbook_exd_job1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecar',
            name='car_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecardepartment', verbose_name='แผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน'),
        ),
    ]
