# Generated by Django 4.2.24 on 2025-10-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0119_basecar_car_dep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercardepartment',
            options={'verbose_name': 'ผู้ใช้และทะเบียนรถและสังกัด', 'verbose_name_plural': 'ข้อมูลผู้ใช้และทะเบียนรถและสังกัด'},
        ),
        migrations.RemoveField(
            model_name='usercardepartment',
            name='car_dep',
        ),
    ]
