# Generated by Django 4.2.24 on 2025-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0120_alter_usercardepartment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='diff_time_job1',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_time_job2',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_time_job3',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_time_job4',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
