# Generated by Django 3.2.5 on 2021-09-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0120_auto_20210908_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ('id',), 'verbose_name': 'ผู้จัดจำหน่าย', 'verbose_name_plural': 'ข้อมูลผู้จัดจำหน่าย'},
        ),
    ]
