# Generated by Django 4.2.24 on 2025-10-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0121_carlogbook_diff_time_job1_carlogbook_diff_time_job2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile_job1',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile งานที่ 1'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile_job2',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile งานที่ 2'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile_job3',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile งานที่ 3'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile_job4',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile งานที่ 4'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile_job5',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile งานที่ 5'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='diff_mile_job6',
            field=models.IntegerField(blank=True, null=True, verbose_name='diff mile งานที่ 6'),
        ),
    ]
