# Generated by Django 4.2.24 on 2025-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0122_carlogbook_diff_mile_carlogbook_diff_mile_job1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecardepartment',
            options={'ordering': ('id',), 'verbose_name': 'แผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน', 'verbose_name_plural': 'ข้อมูลแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน'},
        ),
        migrations.AlterModelOptions(
            name='basejobcardep',
            options={'ordering': ('id',), 'verbose_name': 'รายละเอียดงานและแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน', 'verbose_name_plural': 'ข้อมูลรายละเอียดงานและแผนกทะเบียนรถ/เครื่องจักร/หน่วยงาน'},
        ),
        migrations.AddField(
            model_name='basecar',
            name='pm_round',
            field=models.IntegerField(blank=True, null=True, verbose_name='รอบทำ PM ทุก ๆ (กิโลเมตร หรือ ชั่วโมง)'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mile',
            field=models.IntegerField(blank=True, null=True, verbose_name='เลขไมล์/เลขชั่วโมง ตอนแจ้งซ่อม'),
        ),
    ]
