# Generated by Django 4.2.24 on 2025-12-08 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0123_alter_basecardepartment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmRoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('num_pm', models.IntegerField(blank=True, null=True, verbose_name='เลขที่ทำ PM ล่าสุด')),
                ('ma_id', models.IntegerField(blank=True, null=True, verbose_name='อ้างอิง id Maintenance')),
                ('ma_ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='อ้างอิง ref_no Maintenance')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecar', verbose_name='ทะเบียนรถ/ เครื่องจักร')),
            ],
            options={
                'db_table': 'PmRoundItem',
                'ordering': ('id',),
            },
        ),
    ]
