# Generated by Django 4.2.24 on 2025-12-08 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0124_pmrounditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmrounditem',
            options={'ordering': ('id',), 'verbose_name': 'การทำ PM ล่าสุด', 'verbose_name_plural': 'ข้อมูลการทำ PM ล่าสุด'},
        ),
    ]
