# Generated by Django 3.2.5 on 2021-09-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0125_delete_poitemandcpitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSparesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ชนิดอะไหล่',
                'verbose_name_plural': 'ข้อมูลชนิดอะไหล่',
                'db_table': 'BaseSparesType',
                'ordering': ('id',),
            },
        ),
    ]
