# Generated by Django 4.2.24 on 2025-12-08 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0125_alter_pmrounditem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmrounditem',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ทำ PM'),
        ),
    ]
