# Generated by Django 4.2.24 on 2026-02-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0127_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='job1_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id รายละเอียดงานที่ 1'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='job2_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id รายละเอียดงานที่ 2'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='job3_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id รายละเอียดงานที่ 3'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='job4_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id รายละเอียดงานที่ 4'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='job5_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id รายละเอียดงานที่ 5'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='job6_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id รายละเอียดงานที่ 6'),
        ),
    ]
