# Generated by Django 4.2.24 on 2026-02-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0128_carlogbook_job1_id_carlogbook_job2_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
