# Generated by Django 4.2.24 on 2026-02-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0129_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
