# Generated by Django 4.2.24 on 2026-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0130_carlogbook_is_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOrigSta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อต้นทาง')),
            ],
            options={
                'verbose_name': 'รายละเอียดต้นทางรถขนส่งร้อยเกาะ',
                'verbose_name_plural': 'ข้อมูลรายละเอียดต้นทางรถขนส่งร้อยเกาะ',
                'db_table': 'BaseOrigSta',
                'ordering': ('id',),
            },
        ),
    ]
