# Generated by Django 4.2.24 on 2026-02-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0131_baseorigsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='orig1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig1', to='stock.baseorigsta', verbose_name='ต้นทางรถขนส่งร้อยเกาะ 1'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='orig2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig2', to='stock.baseorigsta', verbose_name='ต้นทางรถขนส่งร้อยเกาะ 2'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='orig3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig3', to='stock.baseorigsta', verbose_name='ต้นทางรถขนส่งร้อยเกาะ 3'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='orig4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig4', to='stock.baseorigsta', verbose_name='ต้นทางรถขนส่งร้อยเกาะ 4'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='orig5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig5', to='stock.baseorigsta', verbose_name='ต้นทางรถขนส่งร้อยเกาะ 5'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='orig6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig6', to='stock.baseorigsta', verbose_name='ต้นทางรถขนส่งร้อยเกาะ 6'),
        ),
    ]
