# Generated by Django 4.2.24 on 2026-02-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0132_carlogbook_orig1_carlogbook_orig2_carlogbook_orig3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comparisonprice',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
