# Generated by Django 4.2.24 on 2026-02-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0133_comparisonprice_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlogbook',
            name='DW_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำกลั่น ( ลิตร )'),
        ),
        migrations.AddField(
            model_name='carlogbook',
            name='coolant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำยาหม้อน้ำ ( ลิตร )'),
        ),
    ]
