# Generated by Django 3.2.5 on 2021-09-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0133_comparisonprice_base_spares_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
