# Generated by Django 4.2.24 on 2026-03-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0134_carlogbook_dw_water_carlogbook_coolant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='DW_water',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำกลั่น ( ขวด )'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='coolant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='น้ำยาหม้อน้ำ ( ขวด )'),
        ),
    ]
