# Generated by Django 4.2.24 on 2026-03-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0135_alter_carlogbook_dw_water_alter_carlogbook_coolant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='force_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ใช้แรง (ชม.)'),
        ),
    ]
