# Generated by Django 4.2.24 on 2026-03-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0136_alter_maintenance_force_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExAPTRNH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docnum', models.CharField(blank=True, max_length=12, null=True)),
                ('refnum', models.CharField(blank=True, max_length=15, null=True)),
                ('ponum', models.CharField(blank=True, max_length=12, null=True)),
                ('docdat', models.DateField(blank=True, null=True)),
                ('duedat', models.DateField(blank=True, null=True)),
                ('comcod', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'APTRNH',
                'indexes': [models.Index(fields=['docnum'], name='APTRNH-ID1'), models.Index(fields=['docdat'], name='APTRNH-ID2')],
                'unique_together': {('comcod', 'docnum')},
            },
        ),
    ]
