# Generated by Django 3.2.5 on 2021-09-15 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0136_alter_comparisonprice_select_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='base_spares_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basesparestype'),
        ),
    ]
