# Generated by Django 4.2.24 on 2026-03-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0137_exaptrnh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exaptrnh',
            options={'verbose_name': 'APTRNH', 'verbose_name_plural': 'APTRNHs'},
        ),
        migrations.AlterModelTable(
            name='exaptrnh',
            table='"APTRNH"',
        ),
    ]
