# Generated by Django 4.2.24 on 2026-03-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0138_alter_exaptrnh_options_alter_exaptrnh_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exaptrnh',
            options={'managed': False, 'verbose_name': 'APTRNH', 'verbose_name_plural': 'APTRNHs'},
        ),
    ]
