# Generated by Django 4.2.29 on 2026-04-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0139_alter_exaptrnh_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชนิดรถ/เครื่องจักร')),
            ],
            options={
                'verbose_name': 'ชนิดรถ/เครื่องจักร',
                'verbose_name_plural': 'ชนิดรถ/เครื่องจักร',
                'db_table': 'BaseCarType',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelTable(
            name='exaptrnh',
            table='APTRNH',
        ),
    ]
