# Generated by Django 3.2.5 on 2021-09-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0139_purchaseorder_approver_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpricedistributor',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='comparisonpricedistributor',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
