# Generated by Django 3.2.5 on 2021-09-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0140_auto_20210916_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpricedistributor',
            name='vat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basevattype'),
        ),
    ]
