# Generated by Django 4.2.29 on 2026-04-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0140_basecartype_alter_exaptrnh_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecar',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecartype', verbose_name='ชนิดรถ/เครื่องจักร'),
        ),
    ]
