# Generated by Django 4.2.29 on 2026-04-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0141_basecar_car_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecartype',
            options={'ordering': ('id',), 'verbose_name': 'ชนิดรถ/เครื่องจักร', 'verbose_name_plural': 'ข้อมูลชนิดรถ/เครื่องจักร'},
        ),
        migrations.AlterField(
            model_name='basecartype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อชนิดรถ/เครื่องจักร'),
        ),
    ]
