# Generated by Django 4.2.29 on 2026-04-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0142_alter_basecartype_options_alter_basecartype_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exoestnd',
            table='"OESTND"',
        ),
        migrations.AlterModelTable(
            name='exoestnh',
            table='"OESTNH"',
        ),
    ]
