# Generated by Django 4.2.29 on 2026-04-22 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0142_alter_basecartype_options_alter_basecartype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaserequisition'),
        ),
    ]
