# Generated by Django 4.2.29 on 2026-05-06 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0143_alter_exoestnd_table_alter_exoestnh_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
    ]
