# Generated by Django 4.2.29 on 2026-04-22 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0143_comparisonprice_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='real_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
