# Generated by Django 4.2.29 on 2026-10-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0144_alter_carlogbook_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='approve_note',
            field=models.TextField(blank=True, null=True, verbose_name='ความคิดเห็นผู้อนุมัติซ่อม'),
        ),
    ]
