# Generated by Django 4.2.29 on 2026-08-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0144_alter_carlogbook_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile_job1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile งานที่ 1'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile_job2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile งานที่ 2'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile_job3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile งานที่ 3'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile_job4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile งานที่ 4'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile_job5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile งานที่ 5'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='diff_mile_job6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='diff mile งานที่ 6'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุด'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end_job1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 1'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end_job2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 2'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end_job3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 3'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end_job4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 4'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end_job5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 5'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_end_job6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์สิ้นสุดงานที่ 6'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่ม'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start_job1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 1'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start_job2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 2'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start_job3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 3'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start_job4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 4'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start_job5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 5'),
        ),
        migrations.AlterField(
            model_name='carlogbook',
            name='mile_start_job6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='เลขไมล์เริ่มต้นงานที่ 6'),
        ),
    ]
