# Generated by Django 4.2.29 on 2026-10-08 10:48
# ฟิลด์ approve_note ถูกเพิ่มใน 0148_maintenance_approve_note แทน
# ไฟล์นี้คงไว้เพื่อให้ DB ที่เคย apply ไปแล้วยังมีประวัติตรงกัน (no-op)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0144_alter_carlogbook_created'),
    ]

    operations = []
