# Generated by Django 4.2.24 on 2026-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0144_alter_carlogbook_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='expenses',
            field=models.ManyToManyField(blank=True, to='stock.baseexpenses', verbose_name='ค่าใช้จ่าย'),
        ),
    ]
