# Generated by Django 4.2.24 on 2026-07-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0145_alter_requisition_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='expenses',
            field=models.ManyToManyField(blank=True, null=True, to='stock.baseexpenses', verbose_name='ค่าใช้จ่าย'),
        ),
        migrations.CreateModel(
            name='PoDownloadLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('downloadAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ดาวน์โหลด')),
                ('downloadUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้โหลด')),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaseorder')),
            ],
            options={
                'verbose_name': 'ประวัติการโหลดใบสั่งซื้อ',
                'verbose_name_plural': 'ข้อมูลประวัติการโหลดใบสั่งซื้อ',
                'db_table': 'PoDownloadLog',
                'ordering': ('id',),
            },
        ),
    ]
