# Generated by Django 4.2.24 on 2026-10-01 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


NEW_TABLES = ('DistributorRuleGroup', 'DistributorRule', 'DistributorCandidate', 'DistributorForm')


def match_distributor_collation(apps, schema_editor):
    """ตาราง Distributor เดิมอาจ collation ไม่ตรงกับค่า default ของ database (เช่น import มาจาก MariaDB)
    ถ้าไม่ปรับตารางใหม่ให้ตรงกัน MySQL จะสร้าง FK -> Distributor.id ไม่ได้ (error 3780)"""
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT CHARACTER_SET_NAME, COLLATION_NAME FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Distributor' AND COLUMN_NAME = 'id'"
        )
        row = cursor.fetchone()
    if row:
        for table in NEW_TABLES:
            schema_editor.execute("ALTER TABLE `%s` CONVERT TO CHARACTER SET %s COLLATE %s" % ((table,) + row))


# หลักเกณฑ์ตามใบขอเพิ่ม Supplier รายใหม่ เข้า ASL (FM-PU-005 Rev.01)
# หมายเหตุในใบ: ข้อ 1, 2, 4 และ 8 หรือ 9 เป็นเกณฑ์ที่ต้องผ่าน ข้อที่เหลือเป็นเกณฑ์เพิ่มเติมตาม ISO
RULE_GROUPS = [
    ('g1', 'ข้อ 1 ความถูกต้องทางกฎหมาย'),
    ('g2', 'ข้อ 2 มีที่อยู่เป็นหลักแหล่ง'),
    ('g4', 'ข้อ 4 คุณสมบัติ (SPEC) คุณภาพผลิตภัณฑ์'),
    ('g89', 'ข้อ 8 หรือ ข้อ 9'),
]
RULES = [
    # (code, name, description, parent code, children_mode, group)
    ('1', 'ความถูกต้องทางกฎหมาย', 'พิจารณาจากใบอนุญาตประกอบกิจการ / หนังสือรับรองบริษัท / ใบ ภพ.20 / บัตรประชาชน / อื่นๆ ที่เกี่ยวข้อง', None, 'all', 'g1'),
    ('2', 'มีที่อยู่เป็นหลักแหล่ง สามารถติดต่อสอบถามข้อมูลได้สะดวก', None, None, 'all', 'g2'),
    ('3', 'ประวัติและผลงานที่เชื่อถือได้', None, None, 'all', None),
    ('4', 'คุณสมบัติ (SPEC) คุณภาพผลิตภัณฑ์', None, None, 'all', 'g4'),
    ('5', 'ราคามีความเหมาะสม', None, None, 'all', None),
    ('6', 'มีเงื่อนไขการชำระเงินเหมาะสม', 'จำนวนวันให้เครดิต กรอกที่ช่อง "เครดิต (วัน)"', None, 'all', None),
    ('7', 'รับประกันผลงาน / บริการหลังการขาย', 'ร้านซ่อมนอก ต้องมีความรับผิดชอบในงานที่รับทำ ถ้างานใช้ไม่ได้ ต้องรับแก้ไข ภายในระยะที่เหมาะสม และยอมรับได้ทั้งสองฝ่าย', None, 'all', None),
    ('8', 'คุณลักษณะของผลิตภัณฑ์ตามมาตรฐานทางด้านสิ่งแวดล้อม และความปลอดภัย', None, None, 'all', 'g89'),
    ('9', 'ระบบบริหารทางด้านคุณภาพสิ่งแวดล้อม อาชีวะอนามัยและความปลอดภัย (ISO 9001 14001 45001)', None, None, 'all', 'g89'),
    ('9.1', 'ผลิตภัณฑ์ / สินค้า (Products)', None, '9', 'all', None),
    ('9.2', 'ผู้จำหน่าย (Supplier)', None, '9', 'all', None),
    ('10', 'สามารถปฏิบัติตามกฎระเบียบด้านสิ่งแวดล้อมความปลอดภัยตามที่บริษัทกำหนด', None, None, 'all', None),
    ('11', 'อื่นๆ', 'ระบุรายละเอียดในช่องหมายเหตุ', None, 'all', None),
]


def seed_rules(apps, schema_editor):
    Group = apps.get_model('stock', 'DistributorRuleGroup')
    Rule = apps.get_model('stock', 'DistributorRule')
    groups = {key: Group.objects.create(name=name, order=i) for i, (key, name) in enumerate(RULE_GROUPS, start=1)}
    rules = {}
    for i, (code, name, description, parent, children_mode, group) in enumerate(RULES, start=1):
        rules[code] = Rule.objects.create(
            code=code, name=name, description=description, parent=rules.get(parent),
            children_mode=children_mode, mandatory_group=groups.get(group), order=i * 10,
        )


def unseed_rules(apps, schema_editor):
    apps.get_model('stock', 'DistributorRule').objects.filter(parent__isnull=False).delete()
    apps.get_model('stock', 'DistributorRule').objects.all().delete()
    apps.get_model('stock', 'DistributorRuleGroup').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0146_positionbasepermission_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_source', models.CharField(choices=[('tomtom', 'TomTom'), ('osm', 'OpenStreetMap')], max_length=20, verbose_name='แหล่งข้อมูลแผนที่')),
                ('place_id', models.CharField(max_length=255, verbose_name='รหัสร้านบนแผนที่')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อบริษัท/ร้านค้า')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขา')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้ติดต่อ')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='โทรศัพท์')),
                ('fax_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='โทรสาร / LINE ID')),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL')),
                ('business_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทธุรกิจ/สินค้า/บริการที่จะใช้')),
                ('credit_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='เครดิต (วัน)')),
                ('shop_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทร้าน (จากแผนที่)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('submitted', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ส่งฟอร์ม')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ/ไม่อนุมัติ')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ไม่อนุมัติ')),
            ],
            options={
                'verbose_name': 'ใบขอเพิ่ม Supplier',
                'verbose_name_plural': 'ข้อมูลใบขอเพิ่ม Supplier',
                'db_table': 'DistributorCandidate',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DistributorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(choices=[('pass', 'ผ่าน'), ('fail', 'ไม่ผ่าน')], max_length=10, verbose_name='ผลพิจารณา')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'คำตอบหลักเกณฑ์ผู้จัดจำหน่าย',
                'verbose_name_plural': 'ข้อมูลคำตอบหลักเกณฑ์ผู้จัดจำหน่าย',
                'db_table': 'DistributorForm',
                'ordering': ('question__order', 'question_id'),
            },
        ),
        migrations.CreateModel(
            name='DistributorRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='ข้อ')),
                ('name', models.CharField(max_length=255, verbose_name='หลักเกณฑ์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('children_mode', models.CharField(choices=[('all', 'ข้อย่อยต้องผ่านทั้งหมด'), ('any', 'ผ่านข้อย่อยข้อใดข้อหนึ่งก็พอ')], default='all', max_length=10, verbose_name='เงื่อนไขข้อย่อย')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
            ],
            options={
                'verbose_name': 'หลักเกณฑ์คัดเลือกผู้จัดจำหน่าย',
                'verbose_name_plural': 'ข้อมูลหลักเกณฑ์คัดเลือกผู้จัดจำหน่าย',
                'db_table': 'DistributorRule',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DistributorRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อกลุ่ม')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'กลุ่มเกณฑ์บังคับผู้จัดจำหน่าย',
                'verbose_name_plural': 'ข้อมูลกลุ่มเกณฑ์บังคับผู้จัดจำหน่าย',
                'db_table': 'DistributorRuleGroup',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RunPython(match_distributor_collation, migrations.RunPython.noop, atomic=False),
        migrations.AddField(
            model_name='distributor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสร้านบนแผนที่'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='place_source',
            field=models.CharField(blank=True, choices=[('tomtom', 'TomTom'), ('osm', 'OpenStreetMap')], max_length=20, null=True, verbose_name='แหล่งข้อมูลแผนที่'),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(fields=('place_source', 'place_id'), name='unique_distributor_place'),
        ),
        migrations.AddField(
            model_name='distributorrule',
            name='mandatory_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='stock.distributorrulegroup', verbose_name='กลุ่มเกณฑ์บังคับ'),
        ),
        migrations.AddField(
            model_name='distributorrule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='stock.distributorrule', verbose_name='ข้อหลัก'),
        ),
        migrations.AddField(
            model_name='distributorform',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stock.distributorcandidate', verbose_name='ใบขอเพิ่ม Supplier'),
        ),
        migrations.AddField(
            model_name='distributorform',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='stock.distributorrule', verbose_name='หลักเกณฑ์'),
        ),
        migrations.AddField(
            model_name='distributorcandidate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_candidate_approved', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AddField(
            model_name='distributorcandidate',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.distributor', verbose_name='รหัส Supplier'),
        ),
        migrations.AddField(
            model_name='distributorcandidate',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_candidate_requested', to=settings.AUTH_USER_MODEL, verbose_name='ผู้คัดเลือก'),
        ),
        migrations.AddConstraint(
            model_name='distributorform',
            constraint=models.UniqueConstraint(fields=('candidate', 'question'), name='unique_distributor_form_answer'),
        ),
        migrations.AddConstraint(
            model_name='distributorcandidate',
            constraint=models.UniqueConstraint(fields=('place_source', 'place_id'), name='unique_distributor_candidate_place'),
        ),
        migrations.RunPython(seed_rules, unseed_rules),
    ]
