# Generated by Django 4.2.29 on 2026-10-07 09:13

from django.db import migrations, models
import stock.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0146_positionbasepermission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlogbook',
            name='image_mile',
            field=models.ImageField(blank=True, null=True, upload_to='car_log_book/%Y/%m/%d', validators=[stock.formatChecker.validate_image_upload_size], verbose_name='รูปภาพเลขไมล์เริ่มต้น'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', validators=[stock.formatChecker.validate_image_upload_size], verbose_name='รูปภาพที่ 1'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', validators=[stock.formatChecker.validate_image_upload_size], verbose_name='รูปภาพที่ 2'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', validators=[stock.formatChecker.validate_image_upload_size], verbose_name='รูปภาพที่ 3'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/%Y/%m/%d', validators=[stock.formatChecker.validate_image_upload_size], verbose_name='รูปภาพที่ 4'),
        ),
    ]
