# Generated by Django 4.2.29 on 2026-09-21 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0146_positionbasepermission_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, unique=True, verbose_name='endpoint ของ push service')),
                ('p256dh', models.CharField(max_length=255, verbose_name='public key ของอุปกรณ์')),
                ('auth', models.CharField(max_length=255, verbose_name='auth secret ของอุปกรณ์')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='user agent ตอนสมัคร')),
                ('last_pushed_count', models.IntegerField(default=0, verbose_name='จำนวนที่ push ไปครั้งล่าสุด')),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ push ครั้งล่าสุด')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สมัคร')),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'การสมัครรับแจ้งเตือน Web Push',
                'verbose_name_plural': 'ข้อมูลการสมัครรับแจ้งเตือน Web Push',
                'db_table': 'PushSubscription',
                'ordering': ('id',),
            },
        ),
    ]
