# Generated by Django 4.2.24 on 2026-09-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def match_distributor_collation(apps, schema_editor):
    """ตาราง Distributor เดิมอาจ collation ไม่ตรงกับค่า default ของ database (เช่น import มาจาก MariaDB)
    ถ้าไม่ปรับให้ตรงกัน MySQL จะสร้าง FK distributor_id -> Distributor.id ไม่ได้ (error 3780)"""
    if schema_editor.connection.vendor != 'mysql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT c.CHARACTER_SET_NAME, c.COLLATION_NAME FROM information_schema.COLUMNS c "
            "WHERE c.TABLE_SCHEMA = DATABASE() AND c.TABLE_NAME = 'Distributor' AND c.COLUMN_NAME = 'id'"
        )
        row = cursor.fetchone()
        if row:
            schema_editor.execute(
                "ALTER TABLE `DistributorCandidate` CONVERT TO CHARACTER SET %s COLLATE %s" % row
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0146_positionbasepermission_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_source', models.CharField(choices=[('tomtom', 'TomTom'), ('osm', 'OpenStreetMap')], max_length=20, verbose_name='แหล่งข้อมูลแผนที่')),
                ('place_id', models.CharField(max_length=255, verbose_name='รหัสร้านบนแผนที่')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อร้าน')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='เบอร์โทร')),
                ('shop_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทร้าน')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่เสนอ')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่พิจารณา')),
            ],
            options={
                'verbose_name': 'ผู้จัดจำหน่ายรออนุมัติ',
                'verbose_name_plural': 'ข้อมูลผู้จัดจำหน่ายรออนุมัติ',
                'db_table': 'DistributorCandidate',
                'ordering': ('-requested_at',),
            },
        ),
        migrations.RunPython(match_distributor_collation, migrations.RunPython.noop, atomic=False),
        migrations.AddField(
            model_name='distributor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสร้านบนแผนที่'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='place_source',
            field=models.CharField(blank=True, choices=[('tomtom', 'TomTom'), ('osm', 'OpenStreetMap')], max_length=20, null=True, verbose_name='แหล่งข้อมูลแผนที่'),
        ),
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.UniqueConstraint(fields=('place_source', 'place_id'), name='unique_distributor_place'),
        ),
        migrations.AddField(
            model_name='distributorcandidate',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.distributor', verbose_name='ผู้จัดจำหน่ายที่สร้าง/ผูก'),
        ),
        migrations.AddField(
            model_name='distributorcandidate',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_candidate_requested', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เสนอ'),
        ),
        migrations.AddField(
            model_name='distributorcandidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_candidate_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='ผู้พิจารณา'),
        ),
        migrations.AddConstraint(
            model_name='distributorcandidate',
            constraint=models.UniqueConstraint(fields=('place_source', 'place_id'), name='unique_distributor_candidate_place'),
        ),
    ]
