# Generated by Django 3.2.5 on 2021-09-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0147_alter_purchaseorder_vat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='ref_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
