# Generated by Django 4.2.29 on 2026-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0147_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_banner_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่แสดงแบนเนอร์ครั้งล่าสุด'),
        ),
    ]
