# Generated by Django 3.2.5 on 2021-09-23 06:24

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0148_requisition_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='ref_no',
            field=models.CharField(blank=True, default=stock.models.requisition_ref_number, max_length=500, null=True),
        ),
    ]
