# Generated by Django 3.2.5 on 2021-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0153_alter_purchaserequisition_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='ref_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
