# Generated by Django 3.2.5 on 2021-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0155_alter_purchaserequisition_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='ref_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
