# Generated by Django 3.2.7 on 2021-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0158_auto_20210929_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='approver_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonprice',
            name='examiner_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approver_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approver_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='purchase_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='stockman_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
