# Generated by Django 3.2.5 on 2021-09-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0159_auto_20210930_1409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaserequisition',
            table='PurchaseRequisition',
        ),
    ]
