# Generated by Django 3.2.5 on 2021-10-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0168_comparisonpricedistributor_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionbasepermission',
            name='ap_amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='positionbasepermission',
            name='ap_amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
