# Generated by Django 3.2.5 on 2021-10-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0172_alter_requisition_memorandum_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpricedistributor',
            name='quotation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/quotation/CM/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/quotation/PO/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='memorandum_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/memorandum/%Y/%m/%d'),
        ),
    ]
