# Generated by Django 3.2.5 on 2021-10-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0173_auto_20211029_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonpricedistributor',
            old_name='quotation_pdf',
            new_name='quotation_pdf_cm',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quotation_pdf',
            new_name='quotation_pdf_po',
        ),
    ]
