# Generated by Django 3.2.5 on 2021-11-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0175_auto_20211029_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='pr_ref_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
