# Generated by Django 3.2.5 on 2021-11-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0176_requisition_pr_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='tex',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
