# Generated by Django 3.2.5 on 2021-11-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0180_alter_receive_receive_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive',
            name='receive_update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
