# Generated by Django 3.2.5 on 2021-11-04 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0183_remove_receive_receive_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='receive_update',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
