# Generated by Django 3.2.5 on 2021-11-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0188_purchaseorder_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basedelivery'),
        ),
    ]
