# Generated by Django 3.2.5 on 2021-11-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0192_auto_20211111_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionbasepermission',
            name='base_permission',
        ),
        migrations.AddField(
            model_name='positionbasepermission',
            name='base_permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.basepermission'),
            preserve_default=False,
        ),
    ]
