# Generated by Django 3.2.5 on 2021-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0193_auto_20211111_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionbasepermission',
            name='base_permission',
        ),
        migrations.AddField(
            model_name='positionbasepermission',
            name='base_permission',
            field=models.ManyToManyField(to='stock.BasePermission'),
        ),
    ]
