# Generated by Django 3.2.5 on 2021-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0196_auto_20211112_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visible',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
