# Generated by Django 3.2.5 on 2021-11-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0204_basevisible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='visible',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visible',
            field=models.ManyToManyField(to='stock.BaseVisible'),
        ),
    ]
