# Generated by Django 3.2.5 on 2021-11-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0206_requisitionitem_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.distributor'),
        ),
        migrations.AddField(
            model_name='receive',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receive',
            name='pay',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='receive',
            name='created',
            field=models.DateField(blank=True, max_length=255),
        ),
    ]
