# Generated by Django 3.2.5 on 2021-11-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0207_auto_20211118_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaseorderitem'),
        ),
    ]
