# Generated by Django 3.2.5 on 2021-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0213_auto_20211123_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
