# Generated by Django 3.2.5 on 2021-11-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0217_purchaseorder_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_receive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_receive',
            field=models.BooleanField(default=False),
        ),
    ]
