# Generated by Django 3.2.5 on 2022-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0219_auto_20220102_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDistributorType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'ชนิดของผู้จัดจำหน่าย',
                'verbose_name_plural': 'ข้อมูลชนิดของผู้จัดจำหน่าย',
                'db_table': 'BaseDistributorType',
                'ordering': ('id',),
            },
        ),
    ]
