# Generated by Django 3.2.5 on 2022-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0221_basegenretype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basegenretype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
