# Generated by Django 3.2.5 on 2021-12-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0229_alter_distributor_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprefix',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
