# Generated by Django 3.2.5 on 2021-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0236_remove_baseprefix_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedistributorgenre',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
