# Generated by Django 3.2.5 on 2021-12-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0241_purchaseorder_receive_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
