# Generated by Django 3.2.5 on 2021-12-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0250_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basedepartment'),
        ),
    ]
