# Generated by Django 3.2.5 on 2021-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0255_alter_requisitionitem_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='urgency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
