# Generated by Django 3.2.5 on 2021-12-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0258_auto_20211221_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='name_th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อบริษัทไทย'),
        ),
        migrations.AlterField(
            model_name='baseaffiliatedcompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อบริษัทย่อ'),
        ),
    ]
