# Generated by Django 3.2.5 on 2021-12-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0259_auto_20211221_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='โลโก้บริษัท'),
        ),
    ]
