# Generated by Django 3.2.5 on 2022-01-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0260_baseaffiliatedcompany_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basevattype',
            options={'ordering': ('id',), 'verbose_name': 'ประชนิดภาษี', 'verbose_name_plural': 'ข้อมูลชนิดภาษี'},
        ),
        migrations.AlterField(
            model_name='basevattype',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อชนิดภาษี'),
        ),
    ]
