# Generated by Django 3.2.5 on 2022-01-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0261_auto_20220107_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basevattype',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสชนิดภาษี'),
        ),
    ]
