# Generated by Django 3.2.5 on 2022-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0265_alter_basepermission_ap_amount_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCMType',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสชนิดใบเปรียบเทียบเทียบราคา')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อชนิดใบเปรียบเทียบเทียบราคา')),
            ],
            options={
                'verbose_name': 'ชนิดใบเปรียบเทียบเทียบราคา',
                'verbose_name_plural': 'ข้อมูลชนิดใบเปรียบเทียบเทียบราคา',
                'db_table': 'BaseCMType',
                'ordering': ('id',),
            },
        ),
    ]
