# Generated by Django 3.2.5 on 2022-01-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0267_comparisonprice_cm_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecmtype',
            options={'ordering': ('id',), 'verbose_name': 'ประเภทใบเปรียบเทียบเทียบราคา', 'verbose_name_plural': 'ข้อมูลประเภทใบเปรียบเทียบเทียบราคา'},
        ),
        migrations.AlterField(
            model_name='basecmtype',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสประเภทใบเปรียบเทียบเทียบราคา'),
        ),
        migrations.AlterField(
            model_name='basecmtype',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อประเภทใบเปรียบเทียบเทียบราคา'),
        ),
    ]
