# Generated by Django 3.2.5 on 2022-01-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0268_auto_20220112_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecmtype',
            name='codename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='โค้ด'),
        ),
    ]
