# Generated by Django 3.2.5 on 2022-01-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0269_basecmtype_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
    ]
