# Generated by Django 3.2.5 on 2022-01-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0273_alter_basebranchcompany_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='name_sh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อบริษัทย่อ'),
        ),
        migrations.AlterField(
            model_name='baseaffiliatedcompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='โค้ดบริษัท'),
        ),
    ]
