# Generated by Django 3.2.5 on 2022-01-25 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0274_auto_20220124_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='branch_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='branch_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany'),
        ),
        migrations.AddField(
            model_name='receive',
            name='branch_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='branch_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany'),
        ),
    ]
