# Generated by Django 3.2.5 on 2022-01-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0275_auto_20220125_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='requisit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.requisition'),
        ),
    ]
