# Generated by Django 3.2.5 on 2022-03-01 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0279_purchaseorder_receipt_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 16, 7, 35, 938964)),
        ),
    ]
