# Generated by Django 3.2.5 on 2022-03-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0280_alter_purchaseorder_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
