# Generated by Django 3.2.5 on 2022-04-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0284_auto_20220303_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='select_bidder_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
