# Generated by Django 3.2.5 on 2022-04-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0285_comparisonprice_select_bidder_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='is_re_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_re_approve',
            field=models.BooleanField(default=False),
        ),
    ]
