# Generated by Django 3.2.5 on 2022-04-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0286_auto_20220406_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='เลขที่ผู้เสียภาษี')),
            ],
            options={
                'verbose_name': 'เลขที่ผู้เสียภาษี',
                'verbose_name_plural': 'ข้อมูลเลขที่ผู้เสียภาษี',
                'db_table': 'BaseTax',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basetax'),
        ),
    ]
