# Generated by Django 3.2.5 on 2022-04-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0286_auto_20220406_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อบริษัทไทย')),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อบริษัทอังกฤษ')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='ที่อยู่')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='เบอร์โทร')),
                ('tex', models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขา')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='โลโก้บริษัท')),
            ],
            options={
                'verbose_name': 'ที่อยู่ตามจดทะเบียนบริษัท',
                'verbose_name_plural': 'ข้อมูลที่อยู่ตามจดทะเบียนบริษัท',
                'db_table': 'BaseAdress',
                'ordering': ('id',),
            },
        ),
    ]
