# Generated by Django 3.2.5 on 2022-04-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0289_branchcompanybaseadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress'),
        ),
    ]
