# Generated by Django 3.2.5 on 2022-05-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0293_purchaserequisition_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch_company',
            field=models.ManyToManyField(to='stock.BaseBranchCompany', verbose_name='การมองเห็นแท็ปบริษัท'),
        ),
    ]
