# Generated by Django 3.2.5 on 2022-05-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0294_userprofile_branch_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='ref_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
