# Generated by Django 3.2.5 on 2022-06-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0295_auto_20220519_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpriceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
