# Generated by Django 3.2.5 on 2022-06-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0297_auto_20220617_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity_pr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity_take',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
