# Generated by Django 3.2.5 on 2022-07-04 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0299_auto_20220617_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_user_po', to=settings.AUTH_USER_MODEL),
        ),
    ]
