# Generated by Django 3.2.5 on 2022-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0300_alter_purchaseorder_approver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
