# Generated by Django 3.2.5 on 2023-02-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0309_auto_20221102_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
