# Generated by Django 3.2.5 on 2023-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0310_purchaseorder_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
