# Generated by Django 3.2.5 on 2023-02-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0317_alter_ratedistributor_organizer_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedistributor',
            name='counsel',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
