# Generated by Django 3.2.5 on 2023-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0321_ratedistributor_po'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedistributor',
            name='counsel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
