# Generated by Django 3.2.5 on 2023-04-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0322_alter_ratedistributor_counsel'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='registration_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/registration/distributor/%Y/%m/%d', verbose_name='หนังสือรับรองบริษัท'),
        ),
    ]
