# Generated by Django 3.2.5 on 2023-05-10 03:16

from django.db import migrations
import stock.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0325_alter_comparisonpricedistributor_quotation_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quotation_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/quotation/PO/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='receipt_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/receipt/RC_PO/%Y/%m/%d'),
        ),
    ]
