# Generated by Django 3.2.5 on 2023-05-10 03:40

from django.db import migrations
import stock.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0326_auto_20230510_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='registration_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/registration/distributor/%Y/%m/%d', verbose_name='หนังสือรับรองบริษัท'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/document/'),
        ),
    ]
