"""
Django settings for djangostock project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t#e@_!hkf3c=m!y3js1(1sj6qu^)qdda9-iwiwla%e5=+*_k$p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['https://stormy-retreat-20167.herokuapp.com/']


STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static','media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stock',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap4',
    'stripe',
    'widget_tweaks',
    'django_filters',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangostock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stock.context_processors.menu_link', #สามารถดึง TEMPLATES menu_link ได้จากทุกๆแห่งแล้ว
                'stock.context_processors.counter', #สามารถดึง TEMPLATES counter ได้จากทุกๆแห่งแล้ว
                'stock.context_processors.allApprovePRCounter', #สามารถดึง TEMPLATES approvePendingCounter ได้จากทุกๆแห่งแล้ว
                'stock.context_processors.allApprovePOCounter',
                'stock.context_processors.approveAllCounter',
                'stock.context_processors.allApproveCPCounter',
                'stock.context_processors.isPurchasingPR',
                'stock.context_processors.userVisibleTab',
                'stock.context_processors.purchasingAllConter',
                'stock.context_processors.addPOAll',
                'stock.context_processors.receiveCounter',
                'stock.context_processors.companyVisibleTab',
                'stock.context_processors.document',
            ],

        },
    },
]

WSGI_APPLICATION = 'djangostock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangostockdb',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    }
}

#DATABASES = {'default': dj_database_url.config(conn_max_age=600, ssl_require= True, default='postgres://avnbwhaodyglkp:01efb2b20ec5d27ca465b7a6f7877c67b8c99829513e075ebc9759d9d92792e9@ec2-107-22-245-82.compute-1.amazonaws.com:5432/da60ecbhqm0qsv')}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'th-th'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

PUBLIC_KEY='pk_test_51IzdMHKiE6HamVX7WqKkIKhiGeFpz3rR9ZHriRV2StKN35TZDmc7vphtxppAGHx9iG0gt6CqYgn2a0BhQZocczBw00rAq31PBT'
SECRET_KEY='sk_test_51IzdMHKiE6HamVX71KKMhE2F0ZLINGFBuZkMYnGyUL3adyL5JFUEVkqE0BxSdKIcu5fqPRpPlbUhRa30JobB39du00pweAykb7'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#SMTP Configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'southerngroup.stock@gmail.com'
#EMAIL_HOST_PASSWORD = 'cqbrdkkwyiuzhthd'
EMAIL_HOST_PASSWORD = 'sviqgnrvbfzggcjx'