# Generated by Django 3.2.3 on 2021-06-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_requisitionitem_chief_approve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='chief_approve_status',
        ),
    ]
