# Generated by Django 3.2.3 on 2021-06-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_requisitionitem_chief_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='chief_approve_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chief_approve_status_set', to='stock.baseapprovestatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='supplies_approve_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='supplies_approve_status_set', to='stock.baseapprovestatus'),
            preserve_default=False,
        ),
    ]
