# Generated by Django 3.2.3 on 2021-06-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20210628_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='chief_approve_status',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='supplies_approve_status',
        ),
    ]
