# Generated by Django 3.2.3 on 2021-07-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_requisitionitem_desired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='chief_approve_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisition',
            name='supplies_approve_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='chief_approve_status',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='supplies_approve_status',
            field=models.CharField(blank=True, default=3, max_length=255),
            preserve_default=False,
        ),
    ]
