# Generated by Django 3.2.3 on 2021-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20210701_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='chief_approve_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='supplies_approve_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
