# Generated by Django 3.2.5 on 2021-07-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stock', '0031_rename_requisition_requisitiondoc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequisitionDoc',
            new_name='Requisition',
        ),
        migrations.AlterModelTable(
            name='requisition',
            table='Requisition',
        ),
    ]
