# Generated by Django 3.2.5 on 2021-07-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_auto_20210712_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='chief_approve_status',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='chief_approve_user_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='supplies_approve_status',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='supplies_approve_user_id',
        ),
    ]
