# Generated by Django 3.2.5 on 2021-07-15 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0034_auto_20210715_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='chief_approve_user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chief_approve_user_name', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='supplies_approve_user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplies_approve_user_name', to='auth.user'),
            preserve_default=False,
        ),
    ]
