# Generated by Django 3.2.5 on 2021-07-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_requisition_purchase_requisition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'BaseUrgency',
                'ordering': ('id',),
            },
        ),
    ]
