# Generated by Django 3.2.5 on 2021-07-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0054_alter_purchaserequisition_requisition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requisition_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
