# Generated by Django 3.2.5 on 2021-07-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0058_purchaserequisition_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='temp',
        ),
    ]
