# Generated by Django 3.2.5 on 2021-07-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0061_auto_20210719_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('codename_th', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'BasePermission',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Position',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PositionBasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.basepermission')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.position')),
            ],
            options={
                'db_table': 'PositionBasePermission',
                'ordering': ('id',),
            },
        ),
    ]
