# Generated by Django 3.2.5 on 2021-07-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0065_auto_20210721_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='approver_user_id',
        ),
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='stockman_user_id',
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='approver_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approver_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='stockman_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stockman_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='examiner_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examiner_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
