# Generated by Django 3.2.5 on 2021-07-21 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0066_auto_20210721_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approver_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='examiner_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='stockman_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockman_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
