# Generated by Django 3.2.5 on 2021-07-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0067_auto_20210721_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='approver_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_status', to='stock.baseapprovestatus'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='examiner_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner_status', to='stock.baseapprovestatus'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='stockman_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockman_status', to='stock.baseapprovestatus'),
        ),
    ]
