# Generated by Django 3.2.5 on 2021-07-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0069_remove_requisition_reference_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaserequisition',
            old_name='examiner_user_id',
            new_name='examiner_user',
        ),
    ]
