# Generated by Django 3.2.5 on 2021-07-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0072_auto_20210729_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='product',
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
