# Generated by Django 3.2.5 on 2021-08-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0081_auto_20210812_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaseorder'),
            preserve_default=False,
        ),
    ]
