# Generated by Django 3.2.5 on 2021-08-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0094_purchaseorder_vat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='requisit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
