# Generated by Django 3.2.5 on 2021-08-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0096_alter_requisitionitem_requisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='requisit',
        ),
    ]
