# Generated by Django 3.2.5 on 2021-08-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0100_comparisonprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonPriceDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.distributor')),
            ],
            options={
                'db_table': 'ComparisonPriceDistributor',
                'ordering': ('id',),
            },
        ),
    ]
