# Generated by Django 3.2.5 on 2021-08-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0104_comparisonpricedistributor_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpriceitem',
            name='cp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.comparisonprice'),
        ),
    ]
