# Generated by Django 3.2.5 on 2021-08-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0105_comparisonpriceitem_cp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonpriceitem',
            old_name='cp',
            new_name='comparison',
        ),
    ]
