# Generated by Django 3.2.5 on 2021-08-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0107_remove_comparisonpriceitem_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpriceitem',
            name='cp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
