# Generated by Django 3.2.5 on 2021-09-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0109_auto_20210901_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='select_bidder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.distributor'),
            preserve_default=False,
        ),
    ]
