# Generated by Django 3.2.5 on 2021-09-08 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0114_auto_20210908_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseunit'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseunit'),
        ),
    ]
