# Generated by Django 3.2.5 on 2021-09-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0118_basecredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
