# Generated by Django 3.2.5 on 2021-09-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0121_alter_distributor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='cp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.comparisonprice'),
        ),
    ]
