# Generated by Django 3.2.5 on 2021-09-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0122_purchaseorder_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseunit'),
        ),
    ]
