# Generated by Django 3.2.5 on 2021-09-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0124_poitemandcpitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POItemAndCPItem',
        ),
    ]
