# Generated by Django 3.2.5 on 2021-09-14 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0126_basesparestype'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='base_spares_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.basesparestype'),
            preserve_default=False,
        ),
    ]
