# Generated by Django 3.2.5 on 2021-09-14 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0129_alter_comparisonprice_base_spares_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonprice',
            name='base_spares_type',
        ),
    ]
