# Generated by Django 3.2.5 on 2021-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0138_auto_20210915_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approver_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
