# Generated by Django 3.2.5 on 2021-09-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0142_auto_20210917_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='quantity_take',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
