# Generated by Django 3.2.5 on 2021-09-21 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0143_requisitionitem_quantity_take'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.distributor'),
        ),
    ]
