# Generated by Django 3.2.5 on 2021-09-23 08:19

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0156_comparisonprice_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonprice',
            name='ref_no',
            field=models.CharField(blank=True, default=stock.models.comparisonPrice_ref_number, max_length=500, null=True),
        ),
    ]
