# Generated by Django 3.2.5 on 2021-10-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0161_auto_20211014_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecredit'),
        ),
    ]
