# Generated by Django 3.2.5 on 2021-10-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0162_alter_comparisonpricedistributor_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseunit'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='urgency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseurgency'),
        ),
    ]
