# Generated by Django 3.2.5 on 2021-10-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0163_auto_20211015_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='urgency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
