# Generated by Django 3.2.5 on 2021-10-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0166_userprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
