# Generated by Django 3.2.5 on 2021-10-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0171_requisition_memorandum_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='memorandum_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/requisition/%Y/%m/%d'),
        ),
    ]
