# Generated by Django 3.2.5 on 2021-10-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0174_auto_20211029_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisonpricedistributor',
            old_name='quotation_pdf_cm',
            new_name='quotation_pdf',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quotation_pdf_po',
            new_name='quotation_pdf',
        ),
    ]
