# Generated by Django 3.2.5 on 2021-11-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0182_alter_receive_receive_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive',
            name='receive_update',
        ),
    ]
