# Generated by Django 3.2.5 on 2021-11-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0186_comparisonprice_po_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'สถานที่จัดส่ง',
                'verbose_name_plural': 'ข้อมูลสถานที่จัดส่ง',
                'db_table': 'BaseDelivery',
                'ordering': ('id',),
            },
        ),
    ]
