# Generated by Django 3.2.5 on 2021-11-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0195_auto_20211112_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionbasepermission',
            name='base_permission',
        ),
        migrations.AddField(
            model_name='positionbasepermission',
            name='base_permission',
            field=models.ManyToManyField(to='stock.BasePermission'),
        ),
    ]
