# Generated by Django 3.2.5 on 2021-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0201_alter_userprofile_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='visible',
            field=models.CharField(choices=[('1', 'Request'), ('2', 'Approve'), ('3', 'Receive')], max_length=25),
        ),
    ]
