# Generated by Django 3.2.5 on 2021-11-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0203_alter_userprofile_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'แท็บการใช้งาน',
                'verbose_name_plural': 'ข้อมูลแท็บการใช้งาน',
                'db_table': 'BaseVisible',
                'ordering': ('id',),
            },
        ),
    ]
