# Generated by Django 3.2.5 on 2021-11-19 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0208_alter_receiveitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='vat_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.basevattype'),
            preserve_default=False,
        ),
    ]
