# Generated by Django 3.2.5 on 2021-11-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0212_alter_comparisonpricedistributor_total_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='total_after_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
