# Generated by Django 3.2.5 on 2021-11-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0216_auto_20211123_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaserequisition'),
        ),
    ]
