# Generated by Django 3.2.5 on 2022-01-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0218_auto_20211125_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='id_express',
        ),
        migrations.AlterField(
            model_name='distributor',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
