# Generated by Django 3.2.5 on 2021-12-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0223_auto_20220102_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAffiliatedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'สังกัดบริษัท',
                'verbose_name_plural': 'ข้อมูลสังกัดบริษัท',
                'db_table': 'BaseAffiliatedCompany',
                'ordering': ('id',),
            },
        ),
    ]
