# Generated by Django 3.2.5 on 2021-12-03 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0225_baseprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='affiliated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaffiliatedcompany'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='distributor',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecredit'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basedistributorgenre'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='payment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='distributor',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseprefix'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basedistributortype'),
        ),
    ]
