# Generated by Django 3.2.5 on 2021-12-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0234_alter_distributor_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprefix',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
