# Generated by Django 3.2.5 on 2021-12-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0235_auto_20211207_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprefix',
            name='prefix',
        ),
    ]
