# Generated by Django 3.2.5 on 2021-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0237_alter_basedistributorgenre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
