# Generated by Django 3.2.5 on 2021-12-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0239_alter_distributor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='tex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
