# Generated by Django 3.2.5 on 2021-12-17 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0247_auto_20211215_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseunit',
            options={'ordering': ('name',), 'verbose_name': 'หน่วยสินค้า', 'verbose_name_plural': 'ข้อมูลหน่วยสินค้า'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'หมวดหมู่สินค้า', 'verbose_name_plural': 'ข้อมูลหมวดหมู่สินค้า'},
        ),
        migrations.AddField(
            model_name='requisition',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseaffiliatedcompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อบริษัท'),
        ),
        migrations.AlterField(
            model_name='basecredit',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อเครดิต'),
        ),
        migrations.AlterField(
            model_name='basedelivery',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อสถานที่จัดส่ง'),
        ),
        migrations.AlterField(
            model_name='basedistributorgenre',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสประเภทของผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='basedistributorgenre',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อประเภทของผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='basedistributortype',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสชนิดของผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='basedistributortype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อชนิดของผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='basepermission',
            name='ap_amount_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ยอดเงินที่อนุมัติใบเปรียบเทียบมากสุด'),
        ),
        migrations.AlterField(
            model_name='basepermission',
            name='ap_amount_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ยอดเงินที่อนุมัติใบเปรียบเทียบน้อยสุด'),
        ),
        migrations.AlterField(
            model_name='basepermission',
            name='codename',
            field=models.CharField(max_length=255, unique=True, verbose_name='โค้ด'),
        ),
        migrations.AlterField(
            model_name='basepermission',
            name='codename_th',
            field=models.CharField(max_length=255, unique=True, verbose_name='โค้ดไทย'),
        ),
        migrations.AlterField(
            model_name='basepermission',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อสิทธิการทำงาน'),
        ),
        migrations.AlterField(
            model_name='baseprefix',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสคำนำหน้านาม'),
        ),
        migrations.AlterField(
            model_name='baseprefix',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อคำนำหน้านาม'),
        ),
        migrations.AlterField(
            model_name='basesparestype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชนิดอะไหล่'),
        ),
        migrations.AlterField(
            model_name='baseunit',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อหน่วยสินค้า'),
        ),
        migrations.AlterField(
            model_name='baseurgency',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียดระดับความเร่งด่วน'),
        ),
        migrations.AlterField(
            model_name='baseurgency',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อระดับความเร่งด่วน'),
        ),
        migrations.AlterField(
            model_name='basevattype',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อประเภทภาษี'),
        ),
        migrations.AlterField(
            model_name='basevisible',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อแท็บการใช้งาน'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อหมวดหมู่สินค้า'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ลิ้งค์'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขบัญชี'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='affiliated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaffiliatedcompany', verbose_name='สังกัดบริษัท'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecredit', verbose_name='เครดิต'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ยอดวงเงิน'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ส่วนลด'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='แฟกส์'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basedistributorgenre', verbose_name='ประเภทของผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เงื่อนไขการชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseprefix', verbose_name='คำนำหน้า'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เบอร์โทร+เบอร์แฟกส์'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='tex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basedistributortype', verbose_name='ชนิดของผู้จัดจำหน่าย'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อประเภทตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='positionbasepermission',
            name='base_permission',
            field=models.ManyToManyField(to='stock.BasePermission', verbose_name='สิทธิการทำงาน'),
        ),
        migrations.AlterField(
            model_name='positionbasepermission',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.position', verbose_name='ตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaffiliatedcompany', verbose_name='สังกัดบริษัท'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='ใช้งานอยู่'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.category', verbose_name='หมวดหมู่สินค้า'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='รหัสสินค้า'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อสินค้า'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ลิ้งค์'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนสินค้าในสต็อก'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseunit', verbose_name='หน่วยสินค้า'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='วันที่อัพเดท'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.position', verbose_name='ตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/', verbose_name='ลายเซ็น'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visible',
            field=models.ManyToManyField(to='stock.BaseVisible', verbose_name='การมองเห็นแท็ปการใช้งาน'),
        ),
    ]
