# Generated by Django 3.2.5 on 2021-12-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0248_auto_20211217_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อแผนก')),
            ],
            options={
                'verbose_name': 'แผนก',
                'verbose_name_plural': 'ข้อมูลแผนก',
                'db_table': 'BaseDepartment',
                'ordering': ('id',),
            },
        ),
    ]
