# Generated by Django 3.2.5 on 2021-12-17 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0249_basedepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.basedepartment', verbose_name='แผนก'),
            preserve_default=False,
        ),
    ]
