# Generated by Django 3.2.5 on 2021-12-17 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0251_alter_requisition_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
