# Generated by Django 3.2.5 on 2021-12-17 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0252_purchaserequisition_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
