# Generated by Django 3.2.5 on 2021-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0253_alter_purchaserequisition_organizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('id',), 'verbose_name': 'ตำแหน่งงาน', 'verbose_name_plural': 'ข้อมูลตำแหน่งงาน'},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อตำแหน่งงาน'),
        ),
    ]
