# Generated by Django 3.2.5 on 2021-12-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0254_auto_20211218_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='urgency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
