# Generated by Django 3.2.5 on 2021-12-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0257_auto_20211220_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขา'),
        ),
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อบริษัทอังกฤษ'),
        ),
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เบอร์โทร'),
        ),
        migrations.AddField(
            model_name='baseaffiliatedcompany',
            name='tex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี'),
        ),
    ]
