# Generated by Django 3.2.5 on 2022-01-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0266_basecmtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='cm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basecmtype'),
        ),
    ]
