# Generated by Django 3.2.5 on 2022-01-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0272_basebranchcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basebranchcompany',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ชื่อสาขาบริษัท'),
        ),
    ]
