# Generated by Django 3.2.5 on 2022-01-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0276_auto_20220126_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonpricedistributor',
            name='is_select',
            field=models.BooleanField(default=False),
        ),
    ]
