# Generated by Django 3.2.5 on 2022-01-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0277_comparisonpricedistributor_is_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.comparisonprice'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaserequisition'),
        ),
    ]
