# Generated by Django 3.2.5 on 2022-03-01 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0281_alter_purchaseorder_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
