# Generated by Django 3.2.5 on 2022-03-01 09:26

from django.db import migrations, models
import stock.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0282_alter_purchaseorder_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='ref_no',
            field=models.CharField(blank=True, default=stock.models.purchaseOrder_ref_number, max_length=500, null=True, unique=True),
        ),
    ]
