# Generated by Django 3.2.5 on 2022-04-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0288_auto_20220420_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCompanyBaseAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress')),
                ('branch_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basebranchcompany')),
            ],
            options={
                'verbose_name': 'บริษัทและที่อยู่ตามจดทะเบียน',
                'verbose_name_plural': 'ข้อมูลบริษัทและที่อยู่ตามจดทะเบียน',
                'db_table': 'BranchCompanyBaseAdress',
                'ordering': ('id',),
            },
        ),
    ]
