# Generated by Django 3.2.5 on 2022-04-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0290_auto_20220422_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='address_company',
        ),
    ]
