# Generated by Django 3.2.5 on 2022-04-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0291_remove_requisition_address_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='address_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseaddress'),
        ),
    ]
