# Generated by Django 3.2.5 on 2022-06-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0298_auto_20220617_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpriceitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
