# Generated by Django 3.2.5 on 2022-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0301_requisitionitem_quantity_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
    ]
