# Generated by Django 3.2.5 on 2022-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0304_auto_20221026_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonprice',
            name='is_special_approve_cm',
            field=models.BooleanField(default=False),
        ),
    ]
