# Generated by Django 3.2.5 on 2022-11-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0305_comparisonprice_is_special_approve_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIsoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_code', models.CharField(max_length=255, unique=True, verbose_name='รหัส iso ใบขอเบิก')),
                ('pr_code', models.CharField(max_length=255, unique=True, verbose_name='รหัส iso ใบขอซื้อ')),
                ('cm_code', models.CharField(max_length=255, unique=True, verbose_name='รหัส iso ใบเปรียบเทียบ')),
                ('po_code', models.CharField(max_length=255, unique=True, verbose_name='รหัส iso ใบสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'รหัส iso',
                'verbose_name_plural': 'ข้อมูลรหัส iso',
                'db_table': 'BaseIsoCode',
                'ordering': ('id',),
            },
        ),
    ]
