# Generated by Django 3.2.5 on 2023-02-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0311_purchaseorder_is_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/document/')),
            ],
            options={
                'db_table': 'Document',
                'ordering': ('id',),
            },
        ),
    ]
