# Generated by Django 3.2.5 on 2023-02-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0318_ratedistributor_counsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อเกรด')),
            ],
            options={
                'verbose_name': 'หน่วยเกรด',
                'verbose_name_plural': 'ข้อมูลหน่วยเกรด',
                'db_table': 'BaseGrade',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ratedistributor',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.basegrade'),
        ),
    ]
