# Generated by Django 3.2.5 on 2023-03-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0319_auto_20230228_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basegrade',
            options={'ordering': ('name',), 'verbose_name': 'เกรด', 'verbose_name_plural': 'ข้อมูลเกรด'},
        ),
    ]
