# Generated by Django 3.2.5 on 2023-03-09 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0320_alter_basegrade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedistributor',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.purchaseorder'),
        ),
    ]
