# Generated by Django 3.2.5 on 2023-05-09 06:57

from django.db import migrations
import stock.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0323_distributor_registration_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='memorandum_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/memorandum/%Y/%m/%d'),
        ),
    ]
