# Generated by Django 3.2.5 on 2023-05-10 02:11

from django.db import migrations
import stock.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0324_alter_requisition_memorandum_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonpricedistributor',
            name='quotation_pdf',
            field=stock.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='pdfs/quotation/CM/%Y/%m/%d'),
        ),
    ]
