# Generated by Django 4.1.4 on 2024-01-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0327_auto_20230510_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
